### PR TITLE
fix ciab-build

### PR DESCRIPTION
**Pull request by ntheanh201**
Fixed the ciab-build

### CODE REVIEW

**Comment by ntheanh201** [comment]
Can you rerun the tests? @zrhoffman 
I don't know if there's anything related to t3c in this code yet

**Comment by ntheanh201** [comment]
image
The yumserver build failed because the repo server is not available, should we fix the base repo or upgrade the base OS? @zrhoffman

**Comment by ntheanh201** [comment]
I saw you updated the image, so I cherry-picked that commit :)

**Review by zrhoffman — APPROVED** [review]
Looks great, thanks @ntheanh201!

**Pull request merged**
