### PR TITLE
testy PR

### PR DESCRIPTION
**Pull request by zrhoffman**
PR

### CODE REVIEW

**Comment by zrhoffman** [comment]
https://github.com/apache/trafficcontrol/blob/master/traffic_ops/testing/api/v3/servers_test.go#L493-L508

**Comment by zrhoffman** [comment]
https://github.com/apache/trafficcontrol/commit/5e09f1ef212ac4b9feaab4f86c35f6e20a130ca9#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR43-R49

**Comment by rob05c** [comment]
https://github.com/apache/trafficcontrol/blob/master/traffic_monitor/health/event.go#L37-L47

**Comment by rob05c** [comment]
https://github.com/apache/trafficcontrol/blob/eb9cf79ea87da605f38741cb00565718b34b6941/traffic_monitor/config/config.go#L37-L50

**Comment by zrhoffman** [comment]
https://github.com/apache/trafficcontrol/blob/ecb380648ae5854d5ee3cd72fbd32909091b9edb/traffic_ops/testing/api/v3/servers_test.go#L493-L508

**Pull request closed without merging**
